---
# tasks file for remi_repo
- name: Configure remi repo
  yum: name={{ item }} state=present
  with_items:
    - http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
  tags: remi
  
- name: Import remi repo key
  rpm_key: key={{ item }} state=present
  with_items:
    - http://rpms.famillecollet.com/RPM-GPG-KEY-remi
  tags: remi