---
# tasks file for remi_repo
- action: setup
  tags: remi

- include_vars: "{{ ansible_distribution + ansible_distribution_major_version}}.yml"
  tags: remi

- name: Configure remi repo
  yum: name={{ remi_repo_url }} state=present
  tags: remi
  
- name: Import remi repo key
  rpm_key: key={{ item }} state=present
  with_items:
    - http://rpms.famillecollet.com/RPM-GPG-KEY-remi
  tags: remi